version: 2

project_name: time-broker

builds:
  - id: time-broker
    binary: time-broker
    main: ./cmd/time-broker
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}} -X github.com/emoral435/time-broker/internal/provider/google.ClientID={{.Env.GOOGLE_CLIENT_ID}} -X github.com/emoral435/time-broker/internal/provider/google.ClientSecret={{.Env.GOOGLE_CLIENT_SECRET}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

release:
  github:
    owner: emoral435
    name: time-broker
  draft: false
  prerelease: auto
